services:
  backend:
    build: ./back
    image: kbo-back:latest
    container_name: kbo-back-container
    ports:
      - "0.0.0.0:3010:3000"
    volumes:
      - ./back:/back
    networks:
      - internal
  
  mongodb:
    image: mongo:latest
    container_name: kbo-mongo
    ports:
      - '27018:27017'
    volumes:
      - mongodata:/data/db
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - internal

volumes:
  mongodata:
  
networks:
  internal:
    driver: bridge
