services:
  backend:
    build: ./back
    image: kbo-back:latest
    container_name: kbo-back-container
    ports:
      - "3010:3000"
    volumes:
      - ./back:/back
    networks:
      - internal
  
  mongodb:
    image: mongo:latest
    container_name: kbo-mongo
    ports:
      - '27018:27017'
    volumes:
      - mongodata:/data/db
    networks:
      - internal

volumes:
  mongodata:
  
networks:
  internal:
    driver: bridge